# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1943eaacf30cb9170610b81b7a1abc4e7549f317926f8aa6d0ab3c8e0e58a95368f3bc663dfbdce9ac3099b67b55af1e76cb96d01197e9bc41c60d97deb91c30

test:
  secret_key_base: 3e4757d3cf5a0a2b64299f365f1455ae66ef261ae8a3bb91b1452b4e10f69ad717a311c2c86487fc016a595d6a7b9bc10f6b1db5d32ea7209ce16b52e9eea3c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
